version: '3.8'
services:
  admin:
    build: .
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - backend_kashif-network
    restart: unless-stopped

networks:
  backend_kashif-network:
    external: true
